[package]
name = "scheduled-payments-contract-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.scheduled-payments-contract]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.62.1"
default-features = false
